# Service for moodle
apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  ports:
    - port: 80
  selector:
    app: moodle
  type: ClusterIP
  
---

# Deployment of moodle

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moodle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: moodle_image:local
        name: moodle
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume-moodle
          mountPath: "/var/www"
      volumes:
      - name: volume-moodle
        persistentVolumeClaim:
          claimName: volume-moodle
