# Service for moodle
apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  ports:
    - port: 443
  selector:
    app: moodle
    tier: webapp
  type: ClusterIP
  
---

# Deployment of moodle

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
      tier: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: webapp
    spec:
      containers:
      - image: bitnami/moodle:3-debian-9
        name: moodle
        env:
        - name: MARIADB_HOST
          value: moodle-mariadb
        - name: MOODLE_DATABASE_USER
          value: root
        - name: MOODLE_DATABASE_NAME
          value: moodle  
        - name: MOODLE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodledb-pass
              key: password
        ports:
        - containerPort: 443
        volumeMounts:
        - name: volume-moodle
          mountPath: "/bitnami"
      volumes:
      - name: volume-moodle
        persistentVolumeClaim:
          claimName: volume-moodle
