
#------- Volumen en el HDD local (pruebas) -------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/kube-storage"
---

#------- Volume claims ---------------------------------



#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpmysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi

---

#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
