
#------- Volumen en el HDD local (pruebas) -------------

# No se crear치n volumenes ya que se usar치 para las 
# pruebas la clase de almacenamientod de microk8s
# de forma que se definir치n solo los volume claims
# internamente creados por microk8s en:
# 
# /var/snap/microk8s/common/default-storage/
#
# Para un posterior despliege en la nube se definir치 el
# volumen y clase correspondientes.


#------- Volume claims ---------------------------------

#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wp-mysql
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---

#------- Wordpress (datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
