
#------- Volumen en el HDD local (pruebas) -------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /kube-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-master

---

#------- Volume claims ---------------------------------



#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpmysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---

#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
