
#------- Volumen en el HDD local (pruebas) -------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/kube-storage/wp-static"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-wp-mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/kube-storage/wp-mysql"

---
#------- Volume claims ---------------------------------




#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wp-mysql
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---

#------- Wordpress (datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
