
#------- Volumen en el HDD local (pruebas) -------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-wordpress
  labels:
    app: wordpress
    tier: webapp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-wp-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany

---
#------- Volume claims ---------------------------------




#------- Wordpress (base de datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wp-mysql
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---

#------- Wordpress (datos) ---------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
